disk-cache=64M
file-allocation=none
continue=false
split=16
min-split-size=1M
max-tries=3
max-connection-per-server=16
max-download-limit=0
max-upload-limit=0
max-overall-upload-limit=0
max-overall-download-limit=0
allow-overwrite=true
auto-file-renaming=false
